name: medical-machine-learning-env
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - tensorflow
  - tensorboard
  - matplotlib
  - notebook
  - pip
  - jupyter
  - ipykernel